In [2]:
import io
import os
import sys
import time
import math
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics import f1_score

import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
class Classifier(nn.Module):
    def __init__(self, embed_dim, num_class):
        super().__init__()
        self.fc = nn.Linear(embed_dim, num_class)
        self.init_weights()

    def init_weights(self):
        initrange = 0.5
        self.fc.weight.data.uniform_(-initrange, initrange)
        self.fc.bias.data.zero_()

    def forward(self, x):
        return self.fc(x)

In [25]:
clf = Classifier(5, 1)
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(clf.parameters(), lr=4.0)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1, gamma=0.9)

In [41]:
N_EPOCHS = 10
X = torch.rand(1000, 5)
y = torch.tensor(np.random.randint(2, size=1000), dtype=torch.float).view(-1,1)

In [ ]:
train_loss = 0

In [46]:
for i in range(N_EPOCHS):
    print(i)
    optimizer.zero_grad()
    output = clf.forward(X)
    loss = criterion(output, y)
    train_loss += loss.item()
    loss.backward()
    optimizer.step()
    print(train_loss)
    print(list(clf.parameters()))


0
1360.5058872699738
[Parameter containing:
tensor([[145.0599, 143.4603, 140.9775, 140.8455, 145.6968]],
       requires_grad=True), Parameter containing:
tensor([275.6641], requires_grad=True)]
1
411110.47463727
[Parameter containing:
tensor([[-2521.5676, -2494.1392, -2449.4731, -2446.7937, -2532.8196]],
       requires_grad=True), Parameter containing:
tensor([-4786.7158], requires_grad=True)]
2
124297886.47463727
[Parameter containing:
tensor([[43845.7344, 43368.5820, 42593.3242, 42547.1758, 44041.3672]],
       requires_grad=True), Parameter containing:
tensor([83239.3906], requires_grad=True)]
3
37581140638.47464
[Parameter containing:
tensor([[-762395.8750, -754098.9375, -740617.1250, -739814.4375, -765797.4375]],
       requires_grad=True), Parameter containing:
tensor([-1447370.6250], requires_grad=True)]
4
11362562650782.475
[Parameter containing:
tensor([[13256645., 13112379., 12877957., 12864003., 13315793.]],
       requires_grad=True), Parameter containing:
tensor([2516709